### ISSUE TITLE
PETCTL

### ISSUE THREAD

**Issue by Oleg9965** [mvbasov/PETCTL#15]
Здравствуйте Михаил!
Повторил вашу конструкцию PETCTL.
Хотелось бы узнать, возможно ли немного изменить прошивку?
Добавить возможность реверса двигателя.
Что бы при вращении энкодера влево после 0, менялось направление вращения и
отображалось значение скорости со знаком -.

**Comment by mvbasov** [comment]
Думаю, что это не сложно. Но делать не буду. Т.к. у меня нет в этом необходимости. Этот проект не имеет целью сделать что то удобное и универсальное для всех. Делается только для себя. Просто выложил свои наработки.

**Comment by mvbasov** [comment]
См. предыдущий комментарий.

**Comment by mvbasov** [comment]
Думаю, что это не сложно. Но делать не буду. Т.к. у меня нет в этом необходимости. Этот проект не имеет целью сделать что то удобное и универсальное для всех. Делается только для себя. Просто выложил свои наработки.

**Comment by mvbasov** [comment]
См. предыдущей комментарий.
